/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/common/AppButton.vue')['default']
    AppCard: typeof import('./components/common/AppCard.vue')['default']
    AppInput: typeof import('./components/common/AppInput.vue')['default']
    AppLoading: typeof import('./components/common/AppLoading.vue')['default']
    AppModal: typeof import('./components/common/AppModal.vue')['default']
    AppToast: typeof import('./components/common/AppToast.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    MenuCard: typeof import('./components/resto/MenuCard.vue')['default']
    Navbar: typeof import('./components/layout/Navbar.vue')['default']
    OrderSummary: typeof import('./components/resto/OrderSummary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    TableStatusCard: typeof import('./components/resto/TableStatusCard.vue')['default']
  }
}
